#!/usr/bin/with-contenv bash

# Sanitize variables
SANED_VARS=( CREATE_SUBDIR_BY_TRACKERS )
for i in "${SANED_VARS[@]}"
do
  export echo "$i"="${!i//\"/}"
  export echo "$i"="$(echo "${!i}" | tr '[:upper:]' '[:lower:]')"
done

if [ "$CREATE_SUBDIR_BY_TRACKERS" == "yes" ]
then
  # make trackers extra folders
  mkdir -p \
	/downloads/{bajaunapeli,bitspyder,torrentfactory,hachede,hdcity,learnflakes,puntotorrent,tbplus,waffles,xbytes,otros,pedros,cinemaggedon,torrentland,tunetraxx,brokenstones,32pages,lztr,p2pelite,bitgamer,psytorrents,pleasuredome,hdspain,iptorrents,trancetraffic,morethantv,passthepopcorn,gp32spain,gazellegames,opencd,mteam,retrowithin,divteam,racingforme,bibliotik,beyondhd,myanonamouse,ultimategamer,x264,awesomehd,broadcasthenet,bitme,theplace,theshow,thegeeks,thevault,theempire,theoccult,torrentleech,hdbits,zonaq,torrentech,sceneaccess,efectodoppler,musicvids,apollo,passtheheadphones,notwhatcd} \
	/downloads/watch/{bajaunapeli,bitspyder,torrentfactory,hachede,hdcity,learnflakes,puntotorrent,tbplus,waffles,xbytes,otros,pedros,cinemaggedon,torrentland,tunetraxx,brokenstones,32pages,lztr,p2pelite,bitgamer,psytorrents,pleasuredome,hdspain,iptorrents,trancetraffic,morethantv,passthepopcorn,gp32spain,gazellegames,opencd,mteam,retrowithin,divteam,racingforme,bibliotik,beyondhd,myanonamouse,ultimategamer,x264,awesomehd,broadcasthenet,bitme,theplace,theshow,thegeeks,thevault,theempire,theoccult,torrentleech,hdbits,zonaq,torrentech,sceneaccess,efectodoppler,musicvids,apollo,passtheheadphones,notwhatcd}
elif [ "$CREATE_SUBDIR_BY_TRACKERS" == "nothing" ]
then
  # no make extra folders
else
  # make original extra folders (Default)
  mkdir -p /downloads{/completed,/watch}
fi

# make general folders
mkdir -p \
	/config{/log/nginx,/log/rtorrent,/log/rutorrent,/nginx,/nginx/conf.d,/php,/rtorrent/rtorrent_sess,/rutorrent/settings/users,/.irssi} \
	/config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/run{/nginx,/php} \
	/var/lib/nginx/tmp/client_body

# copy config
PREV_DIR=$(pwd)

cd /defaults/rutorrent-conf || exit
	shopt -s globstar nullglob
	for i in *
	do
		[[ ! -e "/config/rutorrent/settings/${i}" ]] && cp -v "${i}" "/config/rutorrent/settings/${i}"
	done

cd "${PREV_DIR}" || exit

[[ ! -e /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf

[[ ! -e /config/nginx/.htpasswd ]] && \
	cp /defaults/.htpasswd /config/nginx/.htpasswd
	
[[ ! -e /config/rtorrent/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /config/rtorrent/rtorrent.rc
cp -pr /config/rutorrent/settings/* /usr/share/webapps/rutorrent/conf/

if [ ! -e "/config/php/php.ini" ]; then
	cp /etc/php7/php.ini /config/php/php.ini
	sed -i -e 's/\(register_argc_argv .*=\).*/\1 On/g' /config/php/php.ini
fi


cp /config/php/php.ini /etc/php7/php.ini

# create symlink for webui files
[[ ! -e /var/www/localhost/rutorrent ]] && ln -s \
/usr/share/webapps/rutorrent /var/www/localhost/rutorrent

# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent/rtorrent_sess/rtorrent.lock

if [ "$CREATE_SUBDIR_BY_TRACKERS" == "yes" ]
then
  # permissions for trakers extra folders
  chown abc:abc \
	/downloads \
	/downloads/watch/{bajaunapeli,bitspyder,torrentfactory,hachede,hdcity,learnflakes,puntotorrent,tbplus,waffles,xbytes,otros,pedros,cinemaggedon,torrentland,tunetraxx,brokenstones,32pages,lztr,p2pelite,bitgamer,psytorrents,pleasuredome,hdspain,iptorrents,trancetraffic,morethantv,passthepopcorn,gp32spain,gazellegames,opencd,mteam,retrowithin,divteam,racingforme,bibliotik,beyondhd,myanonamouse,ultimategamer,x264,awesomehd,broadcasthenet,bitme,theplace,theshow,thegeeks,thevault,theempire,theoccult,torrentleech,hdbits,zonaq,torrentech,sceneaccess,efectodoppler,musicvids,apollo,passtheheadphones,notwhatcd} \
        /downloads/{bajaunapeli,bitspyder,torrentfactory,hachede,hdcity,learnflakes,puntotorrent,tbplus,waffles,xbytes,otros,pedros,cinemaggedon,torrentland,tunetraxx,brokenstones,32pages,lztr,p2pelite,bitgamer,psytorrents,pleasuredome,hdspain,iptorrents,trancetraffic,morethantv,passthepopcorn,gp32spain,gazellegames,opencd,mteam,retrowithin,divteam,racingforme,bibliotik,beyondhd,myanonamouse,ultimategamer,x264,awesomehd,broadcasthenet,bitme,theplace,theshow,thegeeks,thevault,theempire,theoccult,torrentleech,hdbits,zonaq,torrentech,sceneaccess,efectodoppler,musicvids,apollo,passtheheadphones,notwhatcd} 
elif [ "$CREATE_SUBDIR_BY_TRACKERS" == "nothing" ]
then
  # permissions without extra folders
else
  # permissions for original extra folders (Default)
  chown abc:abc \
	/downloads \
	/downloads/watch/ \
        /downloads/completed/ 
fi

chown -R abc:abc \
	/config \
	/run \
	/usr/share/webapps/rutorrent \
	/var/lib/nginx \
	/var/www/localhost/rutorrent

chmod -R 755 /config/rutorrent/profiles
chmod 644 /etc/logrotate.d/*
